
#
# Compile and run MOSEK examples
#
CSC=csc.exe
TrafficNetworkModel.exe: TrafficNetworkModel.cs
	$(CSC) /platform:x64 /debug /out:TrafficNetworkModel.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe TrafficNetworkModel.cs

alan.exe: alan.cs
	$(CSC) /platform:x64 /debug /out:alan.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe alan.cs

baker.exe: baker.cs
	$(CSC) /platform:x64 /debug /out:baker.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe baker.cs

breaksolver.exe: breaksolver.cs
	$(CSC) /platform:x64 /debug /out:breaksolver.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe breaksolver.cs

callback.exe: callback.cs
	$(CSC) /platform:x64 /debug /out:callback.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe callback.cs

cqo1.exe: cqo1.cs
	$(CSC) /platform:x64 /debug /out:cqo1.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe cqo1.cs

ceo1.exe: ceo1.cs
	$(CSC) /platform:x64 /debug /out:ceo1.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe ceo1.cs

pow1.exe: pow1.cs
	$(CSC) /platform:x64 /debug /out:pow1.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe pow1.cs

djc1.exe: djc1.cs
	$(CSC) /platform:x64 /debug /out:djc1.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe djc1.cs

diet.exe: diet.cs
	$(CSC) /platform:x64 /debug /out:diet.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe diet.cs

duality.exe: duality.cs
	$(CSC) /platform:x64 /debug /out:duality.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe duality.cs

elastic.exe: elastic.cs
	$(CSC) /platform:x64 /debug /out:elastic.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe elastic.cs

facility_location.exe: facility_location.cs
	$(CSC) /platform:x64 /debug /out:facility_location.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe facility_location.cs

lo1.exe: lo1.cs
	$(CSC) /platform:x64 /debug /out:lo1.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe lo1.cs

gp1.exe: gp1.cs
	$(CSC) /platform:x64 /debug /out:gp1.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe gp1.cs

logistic.exe: logistic.cs
	$(CSC) /platform:x64 /debug /out:logistic.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe logistic.cs

lownerjohn_ellipsoid.exe: lownerjohn_ellipsoid.cs
	$(CSC) /platform:x64 /debug /out:lownerjohn_ellipsoid.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe lownerjohn_ellipsoid.cs

lpt.exe: lpt.cs
	$(CSC) /platform:x64 /debug /out:lpt.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe lpt.cs

milo1.exe: milo1.cs
	$(CSC) /platform:x64 /debug /out:milo1.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe milo1.cs

mioinitsol.exe: mioinitsol.cs
	$(CSC) /platform:x64 /debug /out:mioinitsol.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe mioinitsol.cs

mico1.exe: mico1.cs
	$(CSC) /platform:x64 /debug /out:mico1.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe mico1.cs

nearestcorr.exe: nearestcorr.cs
	$(CSC) /platform:x64 /debug /out:nearestcorr.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe nearestcorr.cs

opt_server_sync.exe: opt_server_sync.cs
	$(CSC) /platform:x64 /debug /out:opt_server_sync.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe opt_server_sync.cs

parameters.exe: parameters.cs
	$(CSC) /platform:x64 /debug /out:parameters.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe parameters.cs

parallel.exe: parallel.cs
	$(CSC) /platform:x64 /debug /out:parallel.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe parallel.cs

pinfeas.exe: pinfeas.cs
	$(CSC) /platform:x64 /debug /out:pinfeas.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe pinfeas.cs

portfolio_1_basic.exe: portfolio_1_basic.cs
	$(CSC) /platform:x64 /debug /out:portfolio_1_basic.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe portfolio_1_basic.cs

portfolio_2_frontier.exe: portfolio_2_frontier.cs
	$(CSC) /platform:x64 /debug /out:portfolio_2_frontier.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe portfolio_2_frontier.cs

portfolio_3_impact.exe: portfolio_3_impact.cs
	$(CSC) /platform:x64 /debug /out:portfolio_3_impact.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe portfolio_3_impact.cs

portfolio_4_transcost.exe: portfolio_4_transcost.cs
	$(CSC) /platform:x64 /debug /out:portfolio_4_transcost.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe portfolio_4_transcost.cs

portfolio_5_card.exe: portfolio_5_card.cs
	$(CSC) /platform:x64 /debug /out:portfolio_5_card.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe portfolio_5_card.cs

portfolio_6_factor.exe: portfolio_6_factor.cs
	$(CSC) /platform:x64 /debug /out:portfolio_6_factor.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe portfolio_6_factor.cs

primal_svm.exe: primal_svm.cs
	$(CSC) /platform:x64 /debug /out:primal_svm.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe primal_svm.cs

reoptimization.exe: reoptimization.cs
	$(CSC) /platform:x64 /debug /out:reoptimization.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe reoptimization.cs

response.exe: response.cs
	$(CSC) /platform:x64 /debug /out:response.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe response.cs

qcqp_sdo_relaxation.exe: qcqp_sdo_relaxation.cs
	$(CSC) /platform:x64 /debug /out:qcqp_sdo_relaxation.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe qcqp_sdo_relaxation.cs

sdo1.exe: sdo1.cs
	$(CSC) /platform:x64 /debug /out:sdo1.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe sdo1.cs

sdo2.exe: sdo2.cs
	$(CSC) /platform:x64 /debug /out:sdo2.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe sdo2.cs

sdo3.exe: sdo3.cs
	$(CSC) /platform:x64 /debug /out:sdo3.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe sdo3.cs

sospoly.exe: sospoly.cs
	$(CSC) /platform:x64 /debug /out:sospoly.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe sospoly.cs

sudoku.exe: sudoku.cs
	$(CSC) /platform:x64 /debug /out:sudoku.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe sudoku.cs

total_variation.exe: total_variation.cs
	$(CSC) /platform:x64 /debug /out:total_variation.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe total_variation.cs

tsp.exe: tsp.cs
	$(CSC) /platform:x64 /debug /out:tsp.exe /r:..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll /target:exe tsp.cs

all: TrafficNetworkModel.exe alan.exe baker.exe breaksolver.exe callback.exe cqo1.exe ceo1.exe pow1.exe djc1.exe diet.exe duality.exe elastic.exe facility_location.exe lo1.exe gp1.exe logistic.exe lownerjohn_ellipsoid.exe lpt.exe milo1.exe mioinitsol.exe mico1.exe nearestcorr.exe opt_server_sync.exe parameters.exe parallel.exe pinfeas.exe portfolio_1_basic.exe portfolio_2_frontier.exe portfolio_3_impact.exe portfolio_4_transcost.exe portfolio_5_card.exe portfolio_6_factor.exe primal_svm.exe reoptimization.exe response.exe qcqp_sdo_relaxation.exe sdo1.exe sdo2.exe sdo3.exe sospoly.exe sudoku.exe total_variation.exe tsp.exe

clean:
	del TrafficNetworkModel.exe alan.exe baker.exe breaksolver.exe callback.exe cqo1.exe ceo1.exe pow1.exe djc1.exe diet.exe duality.exe elastic.exe facility_location.exe lo1.exe gp1.exe logistic.exe lownerjohn_ellipsoid.exe lpt.exe milo1.exe mioinitsol.exe mico1.exe nearestcorr.exe opt_server_sync.exe parameters.exe parallel.exe pinfeas.exe portfolio_1_basic.exe portfolio_2_frontier.exe portfolio_3_impact.exe portfolio_4_transcost.exe portfolio_5_card.exe portfolio_6_factor.exe primal_svm.exe reoptimization.exe response.exe qcqp_sdo_relaxation.exe sdo1.exe sdo2.exe sdo3.exe sospoly.exe sudoku.exe total_variation.exe tsp.exe

test: TrafficNetworkModel.exe alan.exe baker.exe breaksolver.exe callback.exe cqo1.exe ceo1.exe pow1.exe djc1.exe diet.exe duality.exe elastic.exe facility_location.exe lo1.exe gp1.exe logistic.exe lownerjohn_ellipsoid.exe lpt.exe milo1.exe mioinitsol.exe mico1.exe nearestcorr.exe opt_server_sync.exe parameters.exe parallel.exe pinfeas.exe portfolio_1_basic.exe portfolio_2_frontier.exe portfolio_3_impact.exe portfolio_4_transcost.exe portfolio_5_card.exe portfolio_6_factor.exe primal_svm.exe reoptimization.exe response.exe qcqp_sdo_relaxation.exe sdo1.exe sdo2.exe sdo3.exe sospoly.exe sudoku.exe total_variation.exe tsp.exe
	set PATH=..\..\..\platform\win64x86\bin;%%PATH%%
	copy ..\..\..\platform\win64x86\bin\mosekdotnet11_0.dll .
	TrafficNetworkModel.exe
	alan.exe
	baker.exe
	breaksolver.exe
	callback.exe
	cqo1.exe
	ceo1.exe
	pow1.exe
	djc1.exe
	diet.exe
	duality.exe
	elastic.exe
	facility_location.exe
	lo1.exe
	gp1.exe
	logistic.exe
	lownerjohn_ellipsoid.exe
	lpt.exe
	milo1.exe
	mioinitsol.exe
	mico1.exe
	nearestcorr.exe
	opt_server_sync.exe
	parameters.exe
	parallel.exe
	pinfeas.exe
	portfolio_1_basic.exe
	portfolio_2_frontier.exe
	portfolio_3_impact.exe
	portfolio_4_transcost.exe
	portfolio_5_card.exe
	portfolio_6_factor.exe
	primal_svm.exe
	reoptimization.exe
	response.exe
	qcqp_sdo_relaxation.exe
	sdo1.exe
	sdo2.exe
	sdo3.exe
	sospoly.exe
	sudoku.exe
	total_variation.exe
	tsp.exe
